"""Added date to food model

Revision ID: 01a0e468f7b7
Revises: e8bd3ab84ac9
Create Date: 2023-11-21 15:34:58.409964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a0e468f7b7'
down_revision = 'e8bd3ab84ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
