"""Added new colums to Food model

Revision ID: 434322d89330
Revises: 
Create Date: 2023-11-01 17:42:51.853151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '434322d89330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.Enum('ACTIVITY_ZONE_MINUTES', 'ACTIVITY', 'BREATHING_RATE', 'HEART_RATE', 'HEART_RATE_VARIABILITY', 'SP02', name='activitytype'), nullable=False))

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('saturated_fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trans_fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_carbohydrate_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dietary_fiber_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sugars_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_d_ug', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iron_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium_mg', sa.Float(), nullable=True))
        batch_op.drop_column('nutritional_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutritional_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('potassium_mg')
        batch_op.drop_column('iron_mg')
        batch_op.drop_column('calcium_mg')
        batch_op.drop_column('vitamin_d_ug')
        batch_op.drop_column('protein_g')
        batch_op.drop_column('total_sugars_g')
        batch_op.drop_column('dietary_fiber_g')
        batch_op.drop_column('total_carbohydrate_g')
        batch_op.drop_column('sodium_mg')
        batch_op.drop_column('cholesterol_mg')
        batch_op.drop_column('trans_fat_g')
        batch_op.drop_column('saturated_fat_g')
        batch_op.drop_column('total_fat_g')
        batch_op.drop_column('calories')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
