"""Added new fields to Activity model

Revision ID: 442404427cbd
Revises: 45d842070735
Create Date: 2023-11-14 00:54:34.837968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442404427cbd'
down_revision = '45d842070735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('value')

    # ### end Alembic commands ###
