"""Removed column from Food model

Revision ID: 45d842070735
Revises: e0605841131b
Create Date: 2023-11-01 21:35:16.110380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d842070735'
down_revision = 'e0605841131b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('nutrition_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
