"""Changed activitytype model to support new types

Revision ID: e8bd3ab84ac9
Revises: 442404427cbd
Create Date: 2023-11-14 20:23:09.221591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8bd3ab84ac9'
down_revision = '442404427cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_zone_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('heart_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('breathing_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sp02', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hrv', sa.Float(), nullable=True))
        batch_op.alter_column('activity_type',
               existing_type=postgresql.ENUM('ACTIVITY_ZONE_MINUTES', 'ACTIVITY', 'BREATHING_RATE', 'HEART_RATE', 'HEART_RATE_VARIABILITY', 'SP02', name='activitytype'),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('activity_type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('ACTIVITY_ZONE_MINUTES', 'ACTIVITY', 'BREATHING_RATE', 'HEART_RATE', 'HEART_RATE_VARIABILITY', 'SP02', name='activitytype'),
               existing_nullable=False)
        batch_op.drop_column('hrv')
        batch_op.drop_column('sp02')
        batch_op.drop_column('breathing_rate')
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('duration')
        batch_op.drop_column('activity_zone_minutes')

    # ### end Alembic commands ###
